run_name: ppo_pendulum_20250822-192147
algo: ppo
env: pendulum
started_at: '2025-08-22T19:21:47'
train_config:
  num_epochs: 10
  sub_batch_size: 64
  max_grad_norm: 1.0
extra:
  frames_per_batch: 1000
  device: cpu
